version: "3.7"
services:
  db:
    image: postgres
    container_name: "postgres"
    environment:
        - TZ=America/Sao_Paulo
        - POSTGRES_PASSWORD=admin
    ports:
      - 5432:5432
    volumes:
      - "mydbdata:/var/lib/postgresql/data"
 
  nosso_mercado_livre_api:
    image: "nosso_mercado_livre_api"
    container_name: "nosso_mercado_livre_api"
    build:
      context: .
      dockerfile: Dockerfile
    environment: 
      - TZ=America/Sao_Paulo
      - ASPNETCORE_ENVIRONMENT=Local
    ports:
      - "5000:80"
      - "443:443"
    depends_on:
      - db

volumes:
  mydbdata:
